from typing import List
import numpy as np
from scipy.ndimage import label
from sho_model.src.parameter_space import ParameterSpace
from sho_model.src.neural_structure import NeuralStructure

def detect_structures(space: ParameterSpace, threshold: float = 0.5) -> List[NeuralStructure]:
    """
    Detects coherent structures within the Parameter Space.
    """
    binary_mask = space.space > threshold
    labeled_array, num_features = label(binary_mask)

    if num_features == 0:
        return []

    print(f"Detected {num_features} coherent structure(s).")

    structures = []
    for i in range(1, num_features + 1):
        coords = set(zip(*np.where(labeled_array == i)))
        structure = NeuralStructure(space, coords)
        structures.append(structure)

    return structures

def calculate_reward(output: np.ndarray, ideal_output: np.ndarray) -> float:
    """
    Calculates a reward score based on the similarity between the model's
    output and the ideal output.

    Args:
        output: The output generated by the model.
        ideal_output: The target or "correct" output.

    Returns:
        A reward score between 0 and 1, where 1 is a perfect match.
    """
    # We use the Mean Squared Error (MSE) and invert it to get a similarity score
    mse = np.mean((output - ideal_output) ** 2)

    # Normalize the reward to be between 0 and 1.
    # We assume the maximum possible MSE is 1 (for values between 0 and 1).
    reward = 1.0 - mse

    return max(0, reward)  # Ensure reward is not negative
